# first playbook
- hosts: all
  tasks:
    - name: Install httpd package
      package:
        name: "httpd"
        state: present
        become: yes
    - name: start the httpd services
      service:
        name: "httpd"
        state: started
        become: yes


